server:
  port: 2007

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #必要参数  一定要
          lowerCaseServiceId: true
      routes:
        - id: test-client
          uri: lb://test-client
          predicates:
            - Path= /test-client/**
          filters:
            - StripPrefix=1
        - id: baidu
          uri: https://www.baidu.com
          predicates:
            - Path= /baidu
          filters:
            - StripPrefix=1


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/

