server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
    register-with-eureka: false

spring:
  application:
    name: test-client


ribbon:
  eureka:
    enable: true
