server:
  port: 8761
  tomcat:
    max-threads: 500


eureka:
  instance:
    lease-renewal-interval-in-seconds: 2  #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-expiration-duration-in-seconds: 6  #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/

spring:
  application:
    name: test-client
feign:
  httpclient:
    enabled: true
