server:
  port: 8761
  tomcat:
    max-threads: 500


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/

spring:
  application:
    name: test-client
feign:
  httpclient:
    enabled: true
