server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/

spring:
  application:
    name: test-service
  config:
        uri: http://localhost:8888/configs


