server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8889/eureka/,http://peer2:8888/eureka/

spring:
  application:
    name: test-service
  config:
        uri: http://localhost:8888/configs


