spring:
  application:
    name: zuul-server

server:
  port: 2006
  tomcat:
    max-threads: 2000

zuul:
  routes:
    zuul-service:
      path: /test-client/**
      serviceId: test-client

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1  #每间隔5s，向服务端发送一次心跳，证明自己依然”存活“
    lease-expiration-duration-in-seconds: 1  #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 3

    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
hystrix:
  metrics:
    enabled: false